### ISSUE TITLE
download fails

### ISSUE THREAD

**Issue by jsfenfen** [themarshallproject/dod1033#2]
Thanks so much for this library! I noticed that `$ make download` fails, probably the URL has changed?  Is this the same file, I noticed there's a quarter available here: https://www.dla.mil/Portals/104/Documents/DispositionServices/LESO/DISP_AllStatesAndTerritories_06302018.xlsx . Ahem, not that it's very current. Hmm. 

Is there a way to get these files that are current-ish? Hmm, more recent files seem to be available in at URLs like this. Hmm. 

https://www.dla.mil/Portals/104/Documents/DispositionServices/LESO/DISP_AllStatesAndTerritories_03312020.xlsx

```
$ make download
mkdir -p data/current
curl 'http://www.dispositionservices.dla.mil/EFOIA-Privacy/Documents/LESO%20Data/Alaska_Louisiana.xls' -o Alaska_Louisiana.xls
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: www.dispositionservices.dla.mil
make: *** [download] Error 6
```

**Comment by tommeagher** [comment]
So, I'm glad you're looking at this data, @jsfenfen, and that you filed this issue. As you can see, that makefile hasn't been updated in 5 years. I should make a note in the README that we haven't maintained the scripts. However, we have been manually collecting the data in the `data/dod_releases/agencylev` folders. There's 4+ years of data in there, including the most recent quarterly reports. I hope that helps.
And if anybody wants to take a crack at updating the data handling scripts here, we will accept PRs!

**Comment by jsfenfen** [comment]
Hah, thanks so much @tommeagher! (I think the data files are all we need, thanks again!).

**Comment by tommeagher** [comment]
@jsfenfen I made some notes in the README to indicate the scripts have not been maintained. Hope the data is useful for you. Please let me know what you end up doing with it. Can email me off-Github too: tmeagher@themarshallproject.org
